#include <AutoItConstants.au3>
#Include <WinAPI.au3>
#include <Misc.au3>
$MousePos = MouseGetPos()

$StartMsg = MsgBox(3, "AutoSearch", "Voulez-vous télécharger les fichiers nécéssaires. " & @CRLF & "Ceci est obligatoire au premier lancement." & @CRLF & @CRLF & "écran 4:3 nécéssaire, Firefox  ou Internet Explorer recommandé, Chrome et Microfost Edge supporté")
If $StartMsg == 6 Then
 DirCreate( @ScriptDir & "\AutoSearch")
 InetGet("https://www.dropbox.com/s/okr4l362eg0vebm/index.html?dl=1", @ScriptDir & "\AutoSearch\index.html", 1)
 InetGet("https://www.dropbox.com/s/ytyh01wghkqe14m/goiglelight.PNG?dl=1", @ScriptDir & "\AutoSearch\goiglelight.png", 1)
 InetGet("https://www.dropbox.com/s/ndawxcazul5cvgr/favicon.ico?dl=1", @ScriptDir & "\AutoSearch\favicon.ico", 1)
 InetGet("https://www.dropbox.com/s/4wrufdibe696d4m/style.css?dl=1", @ScriptDir & "\AutoSearch\style.css", 1)
 InetGet("https://www.dropbox.com/s/ko2leeaplikqocw/click.mp3?dl=1", @ScriptDir & "\AutoSearch\click.mp3", 1)
 InetGet("https://www.dropbox.com/s/jw0h6cst1mlf34g/keyboard.mp3?dl=1", @ScriptDir & "\AutoSearch\keyboard.mp3", 1)
 InetGet("https://www.dropbox.com/s/321npv8pl7vpoau/goigle.css?dl=1", @ScriptDir & "\AutoSearch\goigle.css", 1)
 InetGet("https://www.dropbox.com/s/cnyylf9a9qire58/search.html?dl=1", @ScriptDir & "\AutoSearch\search.html", 1)
ElseIf $StartMsg == 2 Then
 Exit
EndIf

ShellExecute (@ScriptDir & "\AutoSearch\index.html")
WinWaitActive("[ACTIVE]", "")
Sleep(5000)
WinSetState("[ACTIVE]","", @SW_MAXIMIZE)
MsgBox(0,"AutoSearch","Après avoir cliqué sur ok, le script s'éxécutera 5 secondes plus tard")
MouseMove ( 640, 600, 0)

Sleep(5000)
MouseMove ( 640, 600, 0)
MouseClick($MOUSE_CLICK_LEFT)
sleep(1500)
MouseMove (395, 467, 25)
Sleep(1000)
SoundPlay("C:\Users\usr1\Desktop\click.mp3", 1)
MouseClick($MOUSE_CLICK_LEFT)


_MouseTrap(@DesktopWidth, @DesktopHeight, @DesktopWidth, @DesktopHeight)
SoundPlay("C:\Users\usr1\Desktop\keyboard.mp3")
Send("L")
Sleep(50)
Send("e")
Sleep(50)
Send(" ")
Sleep(50)
Send ("f")
Sleep(50)
Send ("o")
Sleep(50)
Send ("r")
Sleep(50)
Send ("u")
Sleep(50)
Send ("m")
Sleep(50)
Send(" ")
Sleep(50)
Send("d")
Sleep(50)
Send("e")
Sleep(50)
Send("s")
Sleep(50)
Send(" ")
Sleep(50)
Send("m")
Sleep(50)
Send("é")
Sleep(50)
Send("t")
Sleep(50)
Send("i")
Sleep(50)
Send("e")
Sleep(50)
Send("r")
Sleep(50)
Send("s")
Sleep(50)
Send(" ")
Sleep(50)
Send("c")
Sleep(50)
Send("'")
Sleep(50)
Send("e")
Sleep(50)
Send("s")
Sleep(50)
Send("t")
Sleep(50)
Send(" ")
Sleep(50)
Send("q")
Sleep(50)
Send("u")
Sleep(50)
Send("o")
Sleep(50)
Send("i")
Sleep(50)
Send(" ")
Sleep(50)
Send("?")

SoundPlay ("")

_MouseTrap()
Sleep(15)
MouseMove ( 640, 600, 0)
Sleep(1000)
MouseMove (555, 545, 25)
Sleep(500)
SoundPlay("C:\Users\usr1\Desktop\click.mp3", 1)
MouseClick ($MOUSE_CLICK_LEFT)
